### ISSUE TITLE
Error on lines 194 and 213 - python not found

### ISSUE THREAD

**Issue by sidobill** [tech-otaku/macos-desktop#8]
Hello community,

been trynna do this through a bash script via intune but without much luck. I might be doing something wrong:
  *I do have python installed* 

`#!/bin/bash
 mkdir /Users/Shared/Wallpaper
cd /Users/Shared/Wallpaper
curl -J -o /Users/Shared/Wallpaper/macos-desktop-main.zip https://codeload.github.com/tech-otaku/macos-desktop/zip/refs/heads/main
unzip macos-desktop-main.zip
cd macos-desktop-main
curl -o 29_12_2022.png https://xxxx.blob.core.windows.net/xxx/Wallpaper/29_12_2022.png 
chmod +x set-desktop.sh
./set-desktop.sh 29_12_2022.png`

terminal output:

` ./set-desktop.sh: line 194: python: command not found
./set-desktop.sh: line 213: python: command not found
./set-desktop.sh: line 213: [: -ge: unary operator expected
The Desktop image has been set to '29_12_2022.png'`

**Comment by sidobill** [comment]
updating lines where `python` to `python3` have supressed error message but yet doesn't change the wallpaper.  Nevertheless, this would mess tings up since I am curling straight from this repo

**Comment by tech-otaku** [comment]
@sidobill

I need to address the issue with Python. macOS Ventura ships only with `python3`. Previous versions ship with at least Python 2 (`python`). As I use `pyenv` to manage Python, the distinction is not so important, but I need to incorporate in the script a test for the installed version of Python.

After running the script using `python3`, can you paste the output from this command:

```
sqlite3 $HOME/Library/Application\ Support/Dock/desktoppicture.db "SELECT data.rowid, data.value, preferences.rowid, preferences.key, preferences.data_id, preferences.picture_id FROM data INNER JOIN preferences ON data.rowid = preferences.data_id"
```

The `value ` column of the `data` table should contain `/path/to/29_12_2022.png`. This'll be repeated 4 times, once for each row in the `preferences` table.

Regards, Steve.

**Comment by sidobill** [comment]
hello Steve, thanks for the rapid response my friend!
the output was just the way you've forseen:
`~ % sqlite3 $HOME/Library/Application\ Support/Dock/desktoppicture.db "SELECT data.rowid, data.value, preferences.rowid, preferences.key, preferences.data_id, preferences.picture_id FROM data INNER JOIN preferences ON data.rowid = preferences.data_id"`
21|29_12_2022.png|81|1|21|3
21|29_12_2022.png|82|1|21|4
21|29_12_2022.png|83|1|21|2
21|29_12_2022.png|84|1|21|1

but I dont get it, I am not running **Ventura**, it is on **Monterey**.

**Comment by tech-otaku** [comment]
@sidobill 

The Desktop wallpaper isn't changing because you need to pass the absolute path of the image to the script: `./set-desktop.sh "/Users/Shared/Wallpaper/macos-desktop-main/29_12_2022.png"` so that the `desktoppicture.db` resembles `21|/Users/Shared/Wallpaper/macos-desktop-main/29_12_2022.png|81|1|21|3`

When using its relative path (`./set-desktop.sh 29_12_2022.png`) the script finds the image, and writes only the filename to the `data` table. However, macOS doesn't know where that file is. 

With regard to Python, I just checked and Monterey doesn't ship with Python 2 (`python`) either. So it may simply be a case of changing `python` to `python3`, but as the script is intended to run under Big Sur, Catalina and Mojave as well I'll check what they shipped before making any changes.

Regards, Steve
